servicedata: 
 service:
  id: 1001
  name: HTTP APIs
  description: Select the units, number, and frequency for HTTP
  strFormula: 
  serviceDimenstions:
    -
      name: request_unit
      dimenstionType: PICKLIST
      picklist:
        -
         name: exact number
         value: 1
        - 
         name: thousands
         value: 1000
        - 
         name: millions
         value: 1000000
        -
         name: billions
         value: 10000000
      rateTable:
        -
         priceMethod: TIERED
         maxValue: 1
         minValue: 300000000
         unitPrice: 0.000001
        -
         priceMethod: TIERED
         maxValue: 300000000
         minValue: 1000000000
         unitPrice: 0.0000009
    -
      name: period
      dimenstionType: PICKLIST
      picklist:
        -
         name: per second
         value: 2628000000
        -
         name: per minute
         value: 43800000
        -
         name: per hour
         value: 730000
        -
         name: per day
         value: 30416
        - 
         name: per month
         value: 1
    -  
     name: sizebytes
     dimenstionType: PICKLIST
     picklist:
       -
        name: bytes
        value: 0.000976563
       -
        name: kb
        value: 1
       -
        name: mb
        value: 1024
    -  
     name: requests
     dimenstionType: INPUT
    -  
     name: sizeunit
     dimenstionType: INPUT
  
eventdata:
   eventList:
    - 
     name: request_unit
     value: 1
    -
     name: period
     value: 1
    -
     name: requests
     value: 1000
    -
     name: sizeunit
     value: 1000
    -
     name: sizebytes
     value: 1