servicedata: 
 service:
  id: 1001
  name: HTTP APIs
  description: Select the units, number, and frequency for HTTP
  strFormula: 
  serviceDimenstions:
    -
      name: request_unit
      dimenstionType: PICKLIST
      picklist:
        -
         name: exact number
         value: 1
        - 
         name: thousands
         value: 1000
        - 
         name: millions
         value: 1000000
        -
         name: billions
         value: 10000000
    -
      name: period
      dimenstionType: PICKLIST
      picklist:
        -
         name: per second
         value: 2628000000
        -
         name: per minute
         value: 43800000
        -
         name: per hour
         value: 730000
        -
         name: per day
         value: 30416
        - 
         name: per month
         value: 1
    -  
     name: sizeunit
     dimenstionType: PICKLIST
     picklist:
       -
        name: bytes
        value: 0.000976563
       -
        name: kb
        value: 1
       -
        name: mb
        value: 1024
    -  
     name: sizeunit
     dimenstionType: INPUT
    -  
     name: sizebytes
     dimenstionType: INPUT
  rateTable: 
    - 
      frequency: ""
      id: "30001"
      maxCharge: ""
      maxQuantity: "300000000"
      minCharge: ""
      minQuantity: "1"
      priceMethod: TIER
      svcCode: "1000"
      svcDimensionName: request_unit
      unitPrice: "0.000001"
    - 
      frequency: ""
      id: "30002"
      maxCharge: ""
      maxQuantity: "1000000000"
      minCharge: ""
      minQuantity: "300000000"
      priceMethod: TIER
      svcCode: "1000"
      svcDimensionName: request_unit
      unitPrice: "0.0000009"